Update task execution list
spring-cloud/spring-cloud-dataflow-ui pull request #1997
Opened 2024-04-09 13:06 UTC by claudiahub

Resolves #1996

2024-04-10 07:39 UTC, oodamien approved these changes

2024-04-11 10:33 UTC, corneil requested changes
The thinexecutions output has `_embedded.taskExecutionThinResourceList` not `_embedded.taskExecutionResourceList`

2024-04-11 12:27 UTC, corneil commented
We also need a change in [task.service.ts](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/21825fac0d3a7d84463e6574282878787d711b15/ui/src/app/shared/api/task.service.ts#L219)

2024-04-12 09:41 UTC, corneil requested changes

2024-04-12 09:41 UTC, corneil commented on ui/src/app/shared/api/task.service.ts
> +      .get<any>(UrlUtilities.calculateBaseApiUrl() + 'tasks/executions', {headers, params})
Why these changes? I was only expecting `tasks/executions` in `getExecutions` to become `tasks/thinexecutions`

2024-04-12 09:57 UTC, claudiahub commented
@corneil when reading the description on https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1996#issue-2232932015 (see the first comment)
I've read the mention to  `_links['tasks/definitions']`. 
Is this is for another purpose, correct ?

2024-04-12 11:52 UTC, corneil commented
> @corneil when reading the description on [#1996 (comment)](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1996#issue-2232932015) (see the first comment) I've read the mention to `_links['tasks/definitions']`. Is this is for another purpose, correct ?

That link was added in case you wanted to use it to retrieve the detail. I believe the UI already has an approach in place which works and does the same thing. When people use the REST API and previously used `tasks/executions` and not use the faster `tasks/thinexecutions` they will want to retrieve the previous level of detail then using the link makes that easy.

2024-04-12 13:51 UTC, corneil commented on ui/src/app/shared/api/task.service.ts
> +      .get<any>(UrlUtilities.calculateBaseApiUrl() + `tasks/executions/${name}?manifest=${manifest}`, {headers})
Do these represent an old error that didn't surface?

2024-04-17 15:08 UTC, closed without merging

2024-04-17 15:08 UTC, oodamien commented
Close for https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1998